language: node_js
node_js:
  - node
  - lts/*
os:
  - linux
addons:
  - chrome: stable
  - firefox: latest
jobs:
  include:
    - stage: build
        script: yarn
    - stage: test
        script: yarn run:ci:chrome
        script: yarn run:ci:firefox