# https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

name: Integration Tests

on:
  push:
    branches: [main]
  schedule:
    - cron: '00 3 1,15 * *' # At the start and middle of the month in the early morning

jobs:
  test-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress - Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          group: 'Linux/Chrome'
          record: true
          project: ./test
          build: yarn
          start: yarn app:ci
          wait-on: 'http://localhost:40000'
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-edge:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress - Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: edge
          group: 'Windows/Edge'
          record: true
          project: ./test
          build: yarn
          start: yarn app:ci
          wait-on: 'http://localhost:40000'
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome90-ff88
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress - Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          group: 'Linux/Firefox'
          record: true
          project: ./test
          build: yarn
          start: yarn app:ci
          wait-on: 'http://localhost:40000'
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
