# https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

name: Integration Tests

on:
  push:
    branches: [main]
  schedule:
    - cron: '00 3 1,15 * *' # At the start and middle of the month in the early morning

jobs:
  test-chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress - Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: false
          project: ./test
          build: yarn
          start: yarn app:ci
          wait-on: 'http://localhost:40000'
